apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
    nodePort: 30008
  selector:
    app: petclinic
